seed_everything: 2022

trainer:
  logger:
    - class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
      init_args:
        save_dir: /logs
        name: ""
        version: ""
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/fmeasure
        mode: max
        filename: checkpoint_{epoch:03d}-precision={val/precision:.3f}-recall={val/recall:.3f}-f1={val/fmeasure:.3f}
        auto_insert_metric_name: False
        verbose: True
        save_top_k: 1
        save_last: True
  benchmark: True
  num_sanity_val_steps: 0
  strategy: ddp_find_unused_parameters_true
  check_val_every_n_epoch: 20
  accelerator: gpu
  devices: 4
  max_epochs: 1000

model:
  hparams:
    ROOT: /seaweedfs/training/dataset/qunhe/PlankAssembly/data/complete/infos
    DATASETS_TRAIN: /seaweedfs/training/dataset/qunhe/PlankAssembly/splits/train.txt
    DATASETS_VALID: /seaweedfs/training/dataset/qunhe/PlankAssembly/splits/valid.txt
    DATASETS_TEST: /seaweedfs/training/dataset/qunhe/PlankAssembly/splits/test.txt
    BATCH_SIZE: 16
    NUM_WORKERS: 4
    LR: 1e-4

    # DATA
    DATA:
      NUM_INPUT_DOF: 4
      NUM_OUTPUT_DOF: 6
      VOCAB_SIZE: 514
      NUM_VIEW: 3
      NUM_TYPE: 2
      MAX_INPUT_LENGTH: 1200
      MAX_OUTPUT_LENGTH: 128
      NUM_BITS: 9

      AUG_RATIO: 0.1
      NOISE_RATIO: 0.15
      NOISE_LENGTH: 0.02

      IMAGE_SIZE: 512

    # IOU Matching
    THRESHOLD: 0.5

    TOKEN:
      END: 512
      PAD: 513

    MODEL:
      IMAGE_MODEL: tiny_vit_21m_512.dist_in22k_ft_in1k
      NUM_MODEL: 512
      NUM_HEAD: 8
      NUM_FEEDFORWARD: 1024
      DROPOUT: 0.2
      ACTIVATION: relu
      NORMALIZE_BEFORE: True
      NUM_DECODER_LAYERS: 6
      PRETRAINED: True
